name = "V"
grammar = "v"
path_suffixes = ["v", "vv", "mod"]
first_line_pattern = '^#!.*\bnode\b'
line_comments = ["// "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "`", end = "`", close = true, newline = true, not_in = ["comment", "string"] },
    { start = "/*", end = "*/", close = true, newline = true, not_in = ["comment", "string"] },
]
word_characters = ["$", "#"]
tab_size = 2

[overrides.element]
line_comments = { remove = true }
block_comment = ["{/*", "*/}"]

[overrides.string]
word_characters = ["-"]
